//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FloorInfo()
        {
            this.FloorMatrices = new HashSet<FloorMatrix>();
            this.ManagerCabins = new HashSet<ManagerCabin>();
            this.SeatAllocations = new HashSet<SeatAllocation>();
            this.SeatDetails = new HashSet<SeatDetail>();
        }
    
        public int FloorId { get; set; }
        public int FloorNo { get; set; }
        public int NoOfSeats { get; set; }
        public Nullable<int> NoOfDirectorRooms { get; set; }
        public Nullable<int> NoOfBoardRooms { get; set; }
        public Nullable<int> NoOfMeetingRooms { get; set; }
        public int OfficeId { get; set; }
    
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorMatrix> FloorMatrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerCabin> ManagerCabins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatAllocation> SeatAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatDetail> SeatDetails { get; set; }
    }
}
