//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerToSeatPoolTemp
    {
        public int MSPId { get; set; }
        public string ManagerId { get; set; }
        public string SeatNo { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SeatDetail SeatDetail { get; set; }
    }
}
