//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officedata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalDeskManagementFinalDBEntities : DbContext
    {
        public DigitalDeskManagementFinalDBEntities()
            : base("name=DigitalDeskManagementFinalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activation> Activations { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FloorInfo> FloorInfoes { get; set; }
        public virtual DbSet<FloorMatrix> FloorMatrices { get; set; }
        public virtual DbSet<ManagerCabin> ManagerCabins { get; set; }
        public virtual DbSet<ManagerToSeatPoolTemp> ManagerToSeatPoolTemps { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<PasswordTrail> PasswordTrails { get; set; }
        public virtual DbSet<SeatAllocation> SeatAllocations { get; set; }
        public virtual DbSet<SeatAllocationHistory> SeatAllocationHistories { get; set; }
        public virtual DbSet<SeatDetail> SeatDetails { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Image> Images { get; set; }
    }
}
