//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.FloorInfoes = new HashSet<FloorInfo>();
            this.FloorMatrices = new HashSet<FloorMatrix>();
            this.ManagerCabins = new HashSet<ManagerCabin>();
            this.SeatAllocations = new HashSet<SeatAllocation>();
            this.SeatDetails = new HashSet<SeatDetail>();
        }
    
        public int OfficeId { get; set; }
        public string OfficeName { get; set; }
        public string Address { get; set; }
        public string Block { get; set; }
        public string ContactNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int City { get; set; }
        public int State { get; set; }
        public int Country { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorInfo> FloorInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorMatrix> FloorMatrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerCabin> ManagerCabins { get; set; }
        public virtual Image Image { get; set; }
        public virtual State State1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatAllocation> SeatAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatDetail> SeatDetails { get; set; }
    }
}
