//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatAllocation
    {
        public int SAId { get; set; }
        public int SeatId { get; set; }
        public System.DateTime AllocatedDate { get; set; }
        public int FloorId { get; set; }
        public int OfficeId { get; set; }
        public string AllocatedEmpId { get; set; }
        public string AllocatedManagerId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual FloorInfo FloorInfo { get; set; }
        public virtual Office Office { get; set; }
        public virtual SeatDetail SeatDetail { get; set; }
    }
}
