//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officedatas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ManagerCabins = new HashSet<ManagerCabin>();
            this.ManagerToSeatPoolTemps = new HashSet<ManagerToSeatPoolTemp>();
            this.SeatAllocations = new HashSet<SeatAllocation>();
            this.SeatAllocations1 = new HashSet<SeatAllocation>();
        }
    
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string ReportingManager { get; set; }
        public string Address { get; set; }
        public string PwdHash { get; set; }
        public string ImageLink { get; set; }
        public int Designation { get; set; }
        public int Department { get; set; }
        public int Country { get; set; }
        public int State { get; set; }
        public int City { get; set; }
        public string SaltHash { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Designation Designation1 { get; set; }
        public virtual State State1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerCabin> ManagerCabins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerToSeatPoolTemp> ManagerToSeatPoolTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatAllocation> SeatAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatAllocation> SeatAllocations1 { get; set; }
    }
}
